# Generated by Django 4.1.7 on 2023-03-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0004_acessorio_cor_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name_plural': 'Acessórios'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name_plural': 'Veículos'},
        ),
    ]
